### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by CasinoYL** [twerkmeister/iLID#3]
When i ran the train.py in the tensorflow, i got this issues. What this mean? Do i need some other things to be done, when I start to run the train program?

**Comment by hotzenklotz** [comment]
Hi @DukeKadho. I don't mean to be rude but with this little information you can not honestly expect that we debug your setup. Please use an IDE and step through the program with a debugger to find your error.

The ValueError indicates that your input training data cannot be read correctly. Perhaps a file path is wrong? Please be mindful that we published this code more than 1.5 years ago and haven't maintained it since. Especially Tensorflow and Caffe have seen many version updates since our release, possibly breaking stuff with newer versions.
